FIND_ITEM_LIST_BY_SEARCH_CONDITION =
SELECT
  I.ITEM_ID,
  I.TITLE,
  I.CONTENT,
  CONCAT(UP.LAST_NAME, CONCAT(' ', UP.FIRST_NAME)) AUTHOR_NAME,
  I.CREATE_TIME,
  COUNT( IC.ITEM_ID ) COMMENT_NUM
FROM
  ITEM I
  LEFT JOIN USER_PROFILE UP
    ON I.USER_ID = UP.USER_ID
  LEFT JOIN ITEM_COMMENT IC
    ON I.ITEM_ID = IC.ITEM_ID
WHERE
  $if(author) {CONCAT(UP.LAST_NAME, UP.FIRST_NAME) LIKE :%author%}
  AND $if(content) {I.CONTENT LIKE :%content%}
  AND $if(tagIds) {EXISTS (
        SELECT
            IT.TAG_ID
        FROM
            ITEM_TAG IT
        WHERE
            I.ITEM_ID = IT.ITEM_ID
            AND IT.TAG_ID IN (:tagIds[]))}
GROUP BY
  I.ITEM_ID,
  I.TITLE,
  I.CONTENT,
  UP.LAST_NAME,
  UP.FIRST_NAME,
  I.CREATE_TIME
ORDER BY
  I.CREATE_TIME DESC