--  ユーザ情報取得用SQL
FIND_USER_INFO_BY_USER_ID =
SELECT
    SYSTEM_ACCOUNT.USER_ID,
    SYSTEM_ACCOUNT.LOGIN_ID,
    USER_PROFILE.FIRST_NAME,
    USER_PROFILE.LAST_NAME,
    DEPARTMENT.DEPT_NAME,
    USER_PROFILE.MAIL_ADDRESS,
    SYSTEM_ACCOUNT.ADMIN_FLAG,
    SYSTEM_ACCOUNT.DELETED_FLAG
FROM SYSTEM_ACCOUNT
    INNER JOIN USER_PROFILE ON SYSTEM_ACCOUNT.USER_ID = USER_PROFILE.USER_ID
    INNER JOIN DEPARTMENT ON USER_PROFILE.DEPT_ID = DEPARTMENT.DEPT_ID
WHERE
    SYSTEM_ACCOUNT.USER_ID = :userId

--  存在ユーザ削除取得用SQL
FIND_EXISTS_USER_INFO_BY_USER_ID =
SELECT
    SYSTEM_ACCOUNT.USER_ID,
    SYSTEM_ACCOUNT.LOGIN_ID,
    USER_PROFILE.FIRST_NAME,
    USER_PROFILE.LAST_NAME,
    DEPARTMENT.DEPT_NAME,
    USER_PROFILE.MAIL_ADDRESS,
    SYSTEM_ACCOUNT.ADMIN_FLAG,
    SYSTEM_ACCOUNT.DELETED_FLAG
FROM SYSTEM_ACCOUNT
    INNER JOIN USER_PROFILE ON SYSTEM_ACCOUNT.USER_ID = USER_PROFILE.USER_ID
    INNER JOIN DEPARTMENT ON USER_PROFILE.DEPT_ID = DEPARTMENT.DEPT_ID
WHERE
    SYSTEM_ACCOUNT.USER_ID = :userId
    AND DELETED_FLAG = '0'
